### ISSUE TITLE
Feature idea: Using pictures in chat input

### ISSUE THREAD

**Issue by andnig** [yetone/avante.nvim#218]
One of the better-working features of cursor is to simply add a screenshot to the chat input and "ask" Claude to create a component similar to the one in the image. Or change the current component according to the image or picture.

Would this be useful or possible for avante?

Great extension by the way!

**Comment by aarnphm** [comment]
supporting image in a terminal is complicated, but I'm not sure if this is even in the scope of this plugin.

**Comment by theesfeld** [comment]
anthropic will accept a base64 encoded image or file
https://docs.anthropic.com/en/docs/build-with-claude/vision

**Comment by aarnphm** [comment]
well ye, we also support openai don't we?

**Comment by wey-gu** [comment]
I am working on a local PR on this during my trip today, will debug and push later(plane about to take off now, wip)

**Comment by aarnphm** [comment]
https://github.com/yetone/avante.nvim/pull/279 provides initial support for clipboard pasting.

Right now if you copy the image and save to clipboard, for claude at least we will add it to the base message.

This feature is current opt-in, so if you want to test out add the following to behaviour:

```lua
behaviour = {
  support_paste_from_clipboard = true,
}
```

**Comment by aarnphm** [comment]
We will still need to support drag and drop.

**Comment by wey-gu** [comment]
oh, i see your #279 already implement it for clipboard 👍🏻

**Comment by aarnphm** [comment]
I will have a follow up coming up soon with support for drag and drop (currently it is kinda magical)

**Comment by aarnphm** [comment]
For everyone that is listening to this thread since https://github.com/yetone/avante.nvim/commit/c635f73748926f214cbc897a0dd2da7418aa4e86 if you wish to have picture support then we recommend u to have `img-clip.nvim` setup. See readme for more information.

Also if anyone has a windows box I will need some help with powershell implementation here (currently windows is disabled, since I don't have a windows machine to test it out) cc @yuchanns

**Comment by aarnphm** [comment]
I will close this as it is implemented.
