### ISSUE TITLE
Incompatible licensing

### ISSUE THREAD

**Issue by gptlang** [yetone/avante.nvim#267]
It seems that large portions of https://github.com/yetone/avante.nvim/blob/main/lua/avante/providers/copilot.lua is copied from [CopilotChat.nvim](https://github.com/CopilotC-Nvim/CopilotChat.nvim/blob/canary/lua/CopilotChat/copilot.lua)

The license for CopilotChat.nvim is GPL 3.0 which is incompatible with Apache. If possible, please either fully re-implement the code there or change your license. Thank you.

(Let me know if that's not possible & we can hopefully work something out. I don't want to be an asshole, just prefer a stricter license around open source.)

**Comment by aarnphm** [comment]
no worries, we will implement it on our end then

**Comment by aarnphm** [comment]
can you check if this satisfies your ask?

**Comment by gptlang** [comment]
Hey, I noticed you moved things around a bit and cited https://github.com/B00TK1D/copilot-api/blob/main/api.py (which is obviously not where you got most of the code from). Notice that `B00TK1D/copilot-api` is for Copilot completions, not chat. I hope you aren't being malicious here but that feels quite disingenuous, especially as there are still code comments directly tracing back to CopilotChat.nvim. 

How about this: Use the GPL license only for that file like so:
```
-- This file is licensed under GPLv3.
-- Credits: https://github.com/CopilotC-Nvim/CopilotChat.nvim/
```

No need to credit us in your readme or anywhere people might see. It just feels shitty to credit the wrong people and try to hide it...

**Comment by yetone** [comment]
Hello, we have removed support for the copilot provider and eliminated all copilot-related code.

https://github.com/yetone/avante.nvim/pull/318

<img width="733" alt="image" src="https://github.com/user-attachments/assets/76696686-8593-466d-b5c2-ef2f93f089da">

**Comment by cjavdev** [comment]
bummer

**Comment by yetone** [comment]
Here's an explanation of why avante.nvim removed support for Copilot:

1. Firstly, Copilot's performance in code modification is poor, far inferior to claude-3.5-sonnet. Maintaining an underperforming provider would significantly increase our iteration costs and cognitive load, which is not worthwhile.

2. Regarding Copilot API requests, we did indeed draw inspiration from some code in [CopilotChat.nvim](https://github.com/CopilotC-Nvim/CopilotChat.nvim/blob/canary/lua/CopilotChat/copilot.lua?rgh-link-date=2024-08-27T06%3A44%3A00Z). However, the relevant code is too simple, just making HTTP requests to the Copilot API. No matter how we reimplemented it, we couldn't truly "implement it on our end". For example, you can see: https://github.com/zed-industries/zed/blob/ad43bbbf5eda59eba65309735472e0be58b4f7dd/crates/copilot/src/copilot_chat.rs#L19. But since we both use Lua, it looks particularly similar.

3. Although I've already added acknowledgments in the README, I don't want to receive too many complaints from the open-source community about point 2 or even have our license changed. So I had to remove it. Please understand.
