### ISSUE TITLE
Removal of `Copilot` provider

### ISSUE THREAD

**Issue by pidgeon777** [yetone/avante.nvim#324]
I see that with this very recent commit, `Copilot` support was dropped:

https://github.com/yetone/avante.nvim/commit/bfa203018eb02bae99632bf4be1f451e97586849

Is there any reason for this? There are so many `Copilot` users with an active subscription, that's such a pity.

Any chance it will be added back?

**Comment by yetone** [comment]
https://github.com/yetone/avante.nvim/issues/267#issuecomment-2315354301

**Comment by yetone** [comment]
If you need to use Copilot, please find a solution to convert Copilot into an OpenAI Compatible API on your own, and take responsibility for it yourself.

**Comment by chgara** [comment]
> If you need to use Copilot, please find a solution to convert Copilot into an OpenAI Compatible API on your own, and take responsibility for it yourself.

Ouch, it was a nice feature to have because of the unlimited calls that you can make. Etiher way I understand the reasons about it. Your project, your work, your decissions.

Although it should be posible to create a kind of interface to interact with the copilot api as it were openai
I am not a pro of lua, but if maybe others could help we could try to make it viable, what you think @pidgeon777 ?
(https://github.com/B00TK1D/copilot-api/blob/27e36477866311ec9501f34b1fd95cb6d5a88e98/api.py#L91 for reference)

Me alone I am afraid I am not enough to make this scale in the long term, but maybe is easier to create a more public discussion so others can join the initiative, I think many people would want to be able to use their copilot subscription with this amazing plugin.

**Comment by rachartier** [comment]
Really sad to see the owner of CopilotChat act like that. It's a tough loss not being able to use Copilot in Avante anymore

**Comment by yetone** [comment]
Due to the strong demand for Copilot from many people, we will consider reintegrating Copilot into avante.nvim and properly addressing the license issues. I am very sorry for the inconvenience caused.

**Comment by jellydn** [comment]
Jus FYI - Just bring back the copilot provider on my fork if anyone to use https://github.com/jellydn/avante-copilot.nvim

What I did:
 - Bring back copilot provider and add license

https://github.com/jellydn/avante-copilot.nvim/commit/c36ebd8fd7c037b25ba25193a17b2b08073a9cfa

**Comment by rachartier** [comment]
> Due to the strong demand for Copilot from many people, we will consider reintegrating Copilot into avante.nvim and properly addressing the license issues. I am very sorry for the inconvenience caused.

That's really neat. Thank you !

**Comment by aarnphm** [comment]
hi there, I will bring back copilot implementation. I will refer to https://github.com/zed-industries/zed/blob/ad43bbbf5eda59eba65309735472e0be58b4f7dd/crates/copilot/src/copilot_chat.rs#L19 as a implementation pointer.

**Comment by rachartier** [comment]
I've added a """copilot_hack""" provider to the `vendor` from `avante.nvim` on my dotfile. If it can help someone to wait !

[https://github.com/rachartier/dotfiles/blob/main/.config/nvim/lua/api/copilot_api.lua](https://github.com/rachartier/dotfiles/blob/main/.config/nvim/lua/api/copilot_api.lua)

[https://github.com/rachartier/dotfiles/blob/2ea206aa4f23e9f029a21313cf04b6f91421b198/.config/nvim/lua/plugins/ia/copilot.lua#L366](https://github.com/rachartier/dotfiles/blob/2ea206aa4f23e9f029a21313cf04b6f91421b198/.config/nvim/lua/plugins/ia/copilot.lua#L366)

@aarnphm good luck to you, and thank you all for reconsidering this.

**Comment by yetone** [comment]
I've been accused of a lot of things and banned on Reddit r/neovim for 180 days because of this, which has prevented me from responding on Reddit, so I'd like to respond here:

1. First of all, I apologise to CopilotChat.nvim contributor @gptlang for any discomfort I may have caused you by overreacting, and I'm sorry for that, I don't mean to be hostile in any way, and I'm very grateful for CopilotChat.nvim's contributions to Neovim and to the open source world!

Before reviewing the whole thing I'd like to explain a misunderstanding I saw on Reddit:

I never said that CopilotChat.nvim's code is bad, I always said that the copilot **model** is not good for code processing tasks, and as I mentioned in the README for removing the copilot PR, the best model for processing code now is claude-3.5-sonnet, and avante.nvim's The best model for processing code is claude-3.5-sonnet, avante.nvim's functionality has only been tested and guaranteed on this model, we can't guarantee the results of the other models, copilot's model and the openai gpt-4o model have always had serious problems with not following the commands to return the correct line numbers and not returning the correct indentation, it's not realistic to get the best results out of the models except for claude until we completely refactored avante.nvim's prompts, it would be too much of a burden on avante.nvim's feature iteration and maintenance, which would seriously affect the iteration schedule and the users' expectations of how it would work, so I've also expressed in my PR that I'm not adding any new models at this time.

After the explanation I would like to explain the events and my journey (and why I feel this accusation is too serious for me and makes me feel unfair):

1. I didn't write and merge [the code for copilot in avante.nvim](https://github.com/yetone/avante.nvim/pull/116), I didn't review the code (which is a dereliction of duty on my part as a maintainer), and although the code introducer, @aarnphm, has put the code's provenance in the source code, both he and I acknowledge that it is indeed not in compliance with the GPL 3.0 Licence. I specifically stated this to explain that it wasn't true, as someone on Reddit claimed, that I didn't intend to copy CopilotChat.nvim's code (which is what struck me as the most unfair part of the accusation)
2. then got this [Incompatible licensing issue](https://github.com/yetone/avante.nvim/issues/267), at which point I realised that we had copied CopilotChat.nvim's code and were not following the License, and then the introducer of the copilot code responded to this and changed the code (citing https://github.com/B00TK1D/copilot-api/blob/27e36477866311ec9501f34b1fd95cb6d5a88e98/api.py), at which point the issue was shut down by the creator!
3. then I saw the following response on Reddit, to which I responded positively and submitted a [PR](https://github.com/yetone/avante.nvim/pull/302) adding acknowledgments to the README and expressing my thanks to CopilotChat.nvim
	
<img width="803" alt="image" src="https://github.com/user-attachments/assets/7d6752f1-a8fc-4ddd-b170-fe32e7ca94c1">
<img width="2256" alt="image" src="https://github.com/user-attachments/assets/da5d20de-0f95-4065-846f-6cee921584dc">

5. Then I saw that the ‘Incompatible licensing issue’ was re-opened and that `that feels quite disingenuous`, and at that point I realised that the only possible solution was to remove the copilot related code, firstly as I said before since avante.nvim's prompts do not work well on the copilot model (some avante.nvim features are not even available on this model) and are expensive to maintain and iterate on, and secondly, as far as I know, referencing code under the GPL 3.0 does require switching the Licence to GPL 3.0, which is a very high cost, and which I've already spent a lot of time on, it feels quite disingenuous`. I felt that continuing to introduce copilot would affect the normal iteration of avante.nvim, so I decided to remove all the copilot related code and state in the PR that our current functionality is only guaranteed to perform as expected on the claude-3.5-sonnet model, and that we will not be introducing new models for the time being.
6. then I left a comment in ‘Incompatible licensing issue’ that copilot has been removed.
7. then I saw that some people were asking why copilot was removed, so I posted a message on ‘Incompatible licensing issue’ explaining why copilot was removed, and that the wording of my message was indeed inappropriate, and that I accept the accusation and am sorry.

I made this explanation for three reasons:

1. firstly, I apologise to @gptlang.
2. secondly, I saw a false accusation made against me on Reddit and I wanted to explain.
3. as well as seeing people saying that because they don't use avante.nvim anymore, I apologise for that, and don't let my personal behaviour affect the iteration and development of avante.nvim, as our common goal is to make state-of-the-art AI functionality available to Neovim users as well. I promise this will never happen again.

**Comment by aarnphm** [comment]
I guess I will also take full responsibility here as well, I don't think that is fair to blame @yetone on this. 

I will take responsibility and move on

**Comment by gptlang** [comment]
Hi, author of [CopilotChat.nvim](https://github.com/CopilotC-Nvim/CopilotChat.nvim/) here.

I apologize for any drama caused, that was not my intent. I am not on Reddit often and have no relation to what happens on there.

I was curious about the implementation of Copilot Chat so I took a look the implementation. What stood out to me were a few comments that were oddly familiar. If you look at the [initial commit for the file](https://github.com/yetone/avante.nvim/blob/8d52229f16be9d132abcb64fa157189667eaba4a/lua/avante/providers/copilot.lua), you'll find that a lot of strings, comments, and structure is pretty much identical (although with type comments and other stuff removed). 

After opening #267, I got a quick response saying it'll be addressed, so I closed the issue. The next day, I took a look at the file again and saw that some of the comments and strings were still there (though the code definitely changed. It was my bad that I didn't notice how much had changed -- it would've been enough to clear any of the license issues). I sincerely apologize for my overzealous comments. All I needed were some comments and strings to be changed.

I do hope everything goes well for you & will likely use your plugin as well.

(On a side note, I saw tiktoken was removed. I think that's unnecessary since tiktoken is licensed under MIT which is compatible with Apache afaik.)

**Comment by pidgeon777** [comment]
Hello everyone,

> Although it should be possible to create a kind of interface to interact with the Copilot API as if it were OpenAI
> > I am not a pro of Lua, but if maybe others could help we could try to make it viable, what do you think @pidgeon777?

I was also looking for a solution regarding this. In the meantime, I couldn't do anything but fork the `avante.nvim` project, re-adding support for Copilot.

I want to specify that I haven't made it public to respect the authors of the respective plugins and the licensing issues (which I haven't fully understood yet), so I created the branch only for personal use, waiting for an alternative solution.

I see there have been some points of discussion regarding the comparison between the GitHub Copilot Chat model and the Anthrophonic model. In the end, the discussion boils down to comparing the GTP-4o and Claude 3.5 Sonnet models, respectively.

At the moment, the latter might be superior to the former, at least regarding coding, but still many people have a license for Copilot and might "settle" for the performance offered without necessarily subscribing to another service.

Moreover, some of you might know that OpenAI will release an even more powerful model than GPT-4o in the coming months, which could far surpass Claude 3.5 Sonnet. It will be a matter of time before GitHub Copilot Chat adopts the same model, just as it did with GPT-4o.

In the meantime, `avante.nvim` could provide support for Copilot, so when the new model is released, it will already be largely prepared to support it. A user should be able to choose the model to adopt, aware of the relative advantages and disadvantages, if they already have a subscription to it.

Anyway, there are already many AI plugins for Neovim, and I imagine that more or less all of them leverage the currently available models:

- [Awesome Neovim AI Plugins](https://github.com/rockerBOO/awesome-neovim?tab=readme-ov-file#ai)

**Comment by pidgeon777** [comment]
Also, it would be nice to re-add support to `tiktoken`, if licensing allows.

**Comment by yetone** [comment]
Updated, copilot has been re-added: https://github.com/yetone/avante.nvim/pull/381

**Comment by pidgeon777** [comment]
I tested the latest `avante.nvim` commit with `Copilot`, when trying to make a request it returns:

`🚨 Error: 'API request failed with status 400. Body: "Bad Request"'`

My config:

```lua
return {
  -- desc = "Plugin description", -- Warn: Only useful in Extras?
  {
    "yetone/avante.nvim",
    dependencies = {
      "stevearc/dressing.nvim",
      "nvim-lua/plenary.nvim",
      "MunifTanjim/nui.nvim",
      --- The below dependencies are optional,
      "nvim-tree/nvim-web-devicons", -- or echasnovski/mini.icons
      "zbirenbaum/copilot.lua", -- for providers='copilot'
    },
    event = "VeryLazy",
    lazy = false,
    cmd = {
      "AvanteAsk",
    },
    keys = {
      {
        "<leader>3a",
        function()
          require("avante.api").ask()
        end,
        desc = "avante: ask",
        mode = { "n", "v" },
      },
      {
        "<leader>3r",
        function()
          require("avante.api").refresh()
        end,
        desc = "avante: refresh",
      },
      {
        "<leader>3e",
        function()
          require("avante.api").edit()
        end,
        desc = "avante: edit",
        mode = "v",
      },
    },
    opts = function(_, opts)
      local def_opts = {
        setting = "default",
      }

      local my_opts = {
        provider = "copilot",
      }

      opts = vim.tbl_deep_extend("force", opts or {}, my_opts)

      return opts
    end,
    enabled = lvim.builtin.avante.active,
  },
}
```

`Copilot auth` returns: `[Copilot] Authenticated as GitHub user: pidgeon777`.
